### ISSUE TITLE
fails to install (missing deps) 

### ISSUE THREAD

**Issue by whitel** [modularity-modules/cloud-init#1]
-------------------------------` DNF ----------------------------------
    Installed Packages
    dnf.noarch                             2.7.3-1.module_e1d44a88.modularity.1.3fb9e5c                          @anaconda
    libdnf.x86_64                          0.10.1-2.module_e1d44a88.modularity.1                                 @anaconda
    ----------------------------------------------------------------------
    Image built with (KOJI composes):
                    GIT:            https://github.com/container-images/boltron-27
                    Base:           Fedora-Modular-Bikeshed-20171011.n.0
    Image running aginst (KOJI Composes):
                    Bike:   Fedora-Modular-Bikeshed-20171012.n.0

    $ dnf module install cloud-init
    Fedora - Bikeshed - Developmental packages for the next Fedora release                4.7 MB/s | 3.5 MB     00:00    
    Last metadata expiration check: 0:00:00 ago on Fri 13 Oct 2017 02:51:32 PM UTC.
    Error: 
     Problem: package cloud-init-0.7.9-9.module_f8c7dcdc.noarch requires python3-requests, but none of the providers can be installed
      - conflicting requests
      - nothing provides python3-idna needed by python3-requests-2.18.4-1.module_416e449c.noarch

**Comment by KarstenHopp** [comment]
This should be fixed by now as python3-requests got added to python3-ecosystem. This is also using cloud-init:master instead of cloud-init:f7
